### PR TITLE
Add CI workflow

### PR DESCRIPTION
**Pull request by marcinz**
Add a workflow similar to the one in cunumeric.

### CODE REVIEW

**Comment by marcinz** [comment]
@rohany You can see the current results here: https://github.com/marcinz/legate.sparse/actions/runs/3390123843/jobs/5811624439

**Comment by rohany** [comment]
Is this CI set up to use the branches of legate.core and cunumeric that the project depends on? It seems like it must be, because most tests are passing -- where is that configured?

Re the failing tests, can you rebase this branch onto the most recent `main` and try again? The test suite passes for me on that commit both locally and on sapling.

**Comment by marcinz** [comment]
The base image is configured to be built twice per day on my workstation, per suggestion of @magnatelee. So there may be some delay before cunumeric and core changes make it in. I can also rerun the build job manually.

OK, I'll rebase the branch.

**Comment by rohany** [comment]
> The base image is configured to be built twice per day on my workstation, per suggestion of @magnatelee. So there may be some delay before cunumeric and core changes make it in. I can also rerun the build job manually.

I worry that something like this might not be the best. Due to the rate at which legate.core and cunumeric are updated, I frequently need to pull in changes to the branches I maintain of each system, and then need to test that those changes don't break anything. I guess that the tradeoff with specifying the branches as part of the build is that the builds will take even longer, as cunumeric and legate.core are rebuilt as part of each job?

**Comment by rohany** [comment]
> The base image is configured to be built twice per day on my workstation,

Is that base image checked in somewhere? As we try to add the features from my branch of legate.core into the main legate core (for example), we'll need to change the commits of legate.core that we compile against, and eventually use the standard legate core.

**Comment by marcinz** [comment]
Right, the builds would take much longer. When we talked about this with @magnatelee, I think the consensus was that the changes to core and cunumeric will be infrequent. If this is not the case, then the setup we have now would force you to wait for the base image to be rebuilt. I just looked at the branches in question, and I see that they have been touched 11 and 6 days ago. So it seems that the branches don't change frequently?

Yes, the image is pushed to nvcr.io/nvidian/legion/legate-cunumeric-sparse:latest.

**Comment by rohany** [comment]
> So it seems that the branches don't change frequently?

Yeah, it's not too frequently. My question was more in line of -- do I need to have you in the loop every time I want to change the base image? I can see two cases in which i might need it to change:
* I update the tracked branches of legate.core or cunumeric. In this case, I think I just have to wait for the rebuild to happen automatically right?
* I want to stop using a special branch of one of these repositories. This will happen extremely infrequently, at which point having you in the loop is not a large problem.

**Comment by marcinz** [comment]
> I update the tracked branches of legate.core or cunumeric. In this case, I think I just have to wait for the rebuild to happen automatically right?

Yes, the image will be updated automatically.

> I want to stop using a special branch of one of these repositories. This will happen extremely infrequently, at which point having you in the loop is not a large problem.

Using a different branch of the base repos in the CI is rather difficult. Switching the branches on which the CI is based is not possible currently in the CI setup for all our repositories. Currently, we are able to pick the base branch we build against, but this is done by matching the PR branch by name (this is implemented in cunumeric). In general, testing against arbitrary branches is not something we have envisioned, and if we need such a use case, we would need to think about implementing it.

Also, I just thought of this, we could avoid the special purpose build of the base image if there are PRs for your branches in the main cunumeric and legate.core repos. There is a way we already have, as I mentioned above, that allows us to use base images from PRs. Maybe we can discuss this in a voice chat?

**Comment by marcinz** [comment]
So here is a build error I get after updating the branch:

https://github.com/marcinz/legate.sparse/actions/runs/3482908097/jobs/5825784619#step:9:133

**Comment by rohany** [comment]
> Also, I just thought of this, we could avoid the special purpose build of the base image if there are PRs for your branches in the main cunumeric and legate.core repos. There is a way we already have, as I mentioned above, that allows us to use base images from PRs. Maybe we can discuss this in a voice chat?

I can do this. If you want to discuss via voice, we can do that next week -- I'm out at SC this week.

> So here is a build error I get after updating the branch:

I don't know what the cause of this error is, as I can't reproduce that locally. I suspect that the `legate-sparse` branches of both cunumeric and legate.core are out of date in the base image.

**Comment by marcinz** [comment]
The base image is built from the branches linked in the description of legate sparse, so it should be as much up to date as these branches are. I'll take a look and try to figure out why it does not build.

**Comment by rohany** [comment]
I’m not sure then — I only see that error when attempting to build against legate or cunumeric versions behind 22.12.00

**Comment by marcinz** [comment]
I think that the base image may have used cached layers. I changed the build process to always pull the repos. Maybe this was an issue as the cunumeric and legate.core were indeed behind the current state in the base image. I am rebuilding the base image and I'll try it again.

**Comment by marcinz** [comment]
OK, it seems that all but 2-GPU tests pass now. So if you want, you can look at test results here;

https://github.com/marcinz/legate.sparse/actions/runs/3482908097/jobs/5847274061

**Comment by rohany** [comment]
I took a look at the log and found the bugs causing the failures. Can you pull main of legate sparse and try one more time? Everything should pass -- at least it did on sapling for me.

**Comment by rohany** [comment]
> Also, I just thought of this, we could avoid the special purpose build of the base image if there are PRs for your branches in the main cunumeric and legate.core repos. 

PR's have been created now.

**Comment by marcinz** [comment]
All the tests have passed:

https://github.com/marcinz/legate.sparse.public/actions/runs/3499598396/jobs/5935168469

**Comment by marcinz** [comment]
We should be able to attempt a merge now. I will look into using the images from the PRs to the cunumeric and legate.core repos after this is merged.

**Pull request merged**
